### ISSUE TITLE
Using GA in web app for user behavior analyzing

### ISSUE THREAD

**Issue by weitingchou** [weitingchou/toppano.com#17]
It's important to track and understand how users are using our web app and where do they come from. They tracked data is the fundamental basis for us to making enhancements for the app.

**Comment by weitingchou** [comment]
closed this in 
TopPano/verpix-web-app@099cb122c5f2d3403b761b8374fcc59ff0b27c22
TopPano/verpix-web-app@592fc7b83e59049a4fb7af09a0bc5b05091595b9

**Comment by michaeljordan1963** [comment]
可以幫喬登接一下這個嗎？
<img width="1230" alt="2016-06-29 11 51 04" src="https://cloud.githubusercontent.com/assets/20082135/16439963/ed97b672-3def-11e6-9c2c-94fd41887979.png">
