### ISSUE TITLE
加上twitter follow鍵在verpix首頁

### ISSUE THREAD

**Issue by michaeljordan1963** [weitingchou/toppano.com#44]
技術文件連結 https://about.twitter.com/zh-hant/resources/buttons#follow

<img width="144" alt="2016-06-30 12 50 41" src="https://cloud.githubusercontent.com/assets/20082135/16477095/5f57faac-3ec1-11e6-99da-de0e3d09dda4.png">
<img width="515" alt="2016-06-30 12 50 59" src="https://cloud.githubusercontent.com/assets/20082135/16477097/61e28986-3ec1-11e6-8c04-8314c3432891.png">

按鈕的程式碼在下方
<a href="https://twitter.com/verpix" class="twitter-follow-button" data-show-count="false">Follow @verpix</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

**Comment by SuJiaKuan** [comment]
close this in
TopPano/verpix-web-app@37ee65f3b7af9fccdce924ae1a3608fd9be4d8db
